# Generated by Django 5.0.6 on 2024-07-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_rename_address_about_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
